### ISSUE TITLE
Update project name

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-scanner-utils#9]
The `cli` part in the name is confusing and we should find a better name.

I initially added `cli` to make sure we do not use a too generic name given that the aim of this lib is to be shared by addons-linter, customs, and wat.

That being said, one feature provided by this lib is to expose the tools as RPC services, so I can see why having `cli` in the name of the lib is confusing.

@kumar303 suggested `addons-service(-lib)`

**Comment by willdurand** [comment]
cc @mozilla/addons-engineering for ideas

**Comment by diox** [comment]
Whatever you do, don't call it [`nuggets`](https://github.com/mozilla/nuggets/) :)

**Comment by willdurand** [comment]
Maybe it could be `addons-scanner-lib` or `addons-scanner-utils`?

**Comment by muffinresearch** [comment]
`addons-scanner-utils` seems to say what it does quite well. 👍

**Comment by kumar303** [comment]
@diox that's the one! I was trying to remember the name of it. Ha. Since it was unlike any other Python module, it was so hard to track down the actual package for one of those imports.

**Comment by kumar303** [comment]
I suggested `addons-service-*` because CLI scripts and RPC web services both feel like "services" to me. I guess scripts are slightly less so.

**Comment by willdurand** [comment]
@kumar303 would you agree on `addons-scanner-utils`?

**Comment by kumar303** [comment]
Well, isn't it going to be used for more than the scanner? Are we going to
refactor the linter to use the io parts, for example?

**Comment by willdurand** [comment]
> Well, isn't it going to be used for more than the scanner? Are we going to refactor the linter to use the io parts, for example?

The linter is a scanner too. Scanners are tools we apply on addons to gather metrics to me.

**Comment by kumar303** [comment]
Oh, right, duh, they are all scanners. The name sounds good!

**Comment by willdurand** [comment]
@muffinresearch could you please rename this repo to `addons-scanner-utils`? We might want to rename the NPM module too?

**Comment by muffinresearch** [comment]
Done

**Comment by kumar303** [comment]
@willdurand I recommend updating this sentence in the readme and project description: "Various addons related helpers to build CLIs."
